version: '3'
services:
  db:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
  app:
    build: .
    environment:
      REDIS_PORT : 6379
      REDIS_HOST : redis
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    links:
      - "db:db"
    ports:
      - "8080:8080"
    depends_on:
      - db