spring:
  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: user
#    password: password
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST:0.0.0.0}


  cache:
    type: redis

server:
  port: 8080

logging:
  level:
    root: info

hash-thread-pool:
  queueCapacity: 100
  maxPoolSize: 4
  corePoolSize: 4
  threadNamePrefix: "hashPoolThread-"

hash:
  cache:
    maxCapacity: 100
    border: 0.2
  range: 100
  generate-cron: "0 */10 * * * ?"
  clean:
    cron : "0 */10 * * * ?" #every 10 minutes
#    cron : "*/10 * * * * ?" #every 10 seconds
    days: 365
